# Generated by Django 5.2.3 on 2025-06-20 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=60, verbose_name='Бренд')),
                ('title', models.CharField(max_length=120, verbose_name='Название модели')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.URLField(verbose_name='URL картинки')),
                ('price_day_1', models.PositiveIntegerField(verbose_name='Цена за 1 сутки')),
                ('price_days_1_3', models.PositiveIntegerField(verbose_name='Цена за 1–3 суток')),
                ('price_days_3_plus', models.PositiveIntegerField(verbose_name='Цена за 3+ суток')),
            ],
            options={
                'ordering': ['brand', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=120, verbose_name='Вещь (строкой)')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rentals.item')),
            ],
        ),
    ]
